### ISSUE TITLE
Gem version 5.4.0 for Mac OS is incompatible with Ruby 3.2

### ISSUE THREAD

**Issue by carl-t** [ibmdb/ruby-ibmdb#145]
Ruby's old `Dir.exists?` method has been deprecated in Ruby 3.2 but is still being used in `ibm_db.rb` resulting in the following error:

```
undefined method `exists?' for Dir:Class (NoMethodError)
/Users/user1/.gem/ruby/3.2.0/gems/ibm_db-5.4.0/lib/ibm_db.rb:3:in `<top (required)>'
```

The code in question is:
```
if(RUBY_PLATFORM =~ /darwin/i)
   cliPackagePath = File.dirname(__FILE__)  + '/clidriver'
        **if(Dir.exists?(cliPackagePath))**
```

**Comment by praveen-db2** [comment]
@carl-t Or driver supports until Ruby v 3.1.x.
v3.2 support is not yet planned. Thanks for your finding out, we will consider this when we work on to support Ruby v 3.2.
